In [1]:
!pip install -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.4/122.4 MB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 53.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 63.0 MB/s eta 0:00:00
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.19.1
    Uninstalling tokenizers-0.19.1:
      Successfully uninstalled tokenizers-0.19.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.44.2
    Uninstalling transformers-4.44.2:
      Successfully uninstalled transformers-4.44.2


In [2]:
import os
import torch

from transformers import (AutoTokenizer, AutoModelForCausalLM)

In [3]:
os.environ["HF_TOKEN"] = "your_token_here"

In [4]:
model_name="google/gemma-2b-it"

# **Loading the tokenizer and the model**

In [5]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

In [9]:
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", torch_dtype=torch.bfloat16)

`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

# **Asking the model a question**

In [10]:
prompt = "what is machine learning?"

In [14]:
token = tokenizer(prompt, return_tensors="pt").to("cuda")

In [15]:
response = model.generate(**token, max_new_tokens=512)

Starting from v4.46, the `logits` model output will have the same type as the model (except at train time, where it will always be FP32)


In [16]:
response

tensor([[     2,   5049,    603,   6479,   6044, 235336,    109,  24911,   6044,
            591,   3939, 235275,    603,    476,   1334,   2863,    576,  18225,
          17273,    591,  11716, 235275,    674,  25039,  25175,    577,   3918,
            774,   1423,   2346,  19303,  19991, 235265,   1417,   8563,  15051,
            577,   4771,   1024,   4665,   1163,   1069,   1593,    476,   2185,
           3151,   5231,  23435, 168428,    109,    688,   4858, 235303, 235256,
           1368,    665,   3598,  66058,    109, 235274, 235265,   5231,   1510,
          12988,  66058,    714,   1423,    603,  22024, 235269,  31010, 235269,
            578,  30003,   1280,    476,   5920,    674,    573,   6479,    798,
           3508, 235265,    108, 235284, 235265,   5231,   2494,   8492,  66058,
          28398,   6479,   6044,  28514,    708,  12228,   3482,    611,    573,
           1916,    576,   1423,    578,    573,   3210,    577,    614,  23895,
         235265,    108, 235

In [17]:
output = tokenizer.decode(response[0])

In [18]:
print(output)

<bos>what is machine learning?

Machine learning (ML) is a subfield of artificial intelligence (AI) that enables computers to learn from data without explicit programming. This allows machines to improve their performance over time through a process called **training**.

**Here's how it works:**

1. **Data preparation:** The data is gathered, cleaned, and transformed into a format that the machine can understand.
2. **Model selection:** Different machine learning algorithms are chosen based on the type of data and the problem to be solved.
3. **Training:** The data is fed into the model, which learns the patterns and relationships within it.
4. **Evaluation:** The trained model is tested on unseen data to assess its accuracy and performance.
5. **Iteration:** The model is refined and updated based on the evaluation results, and the process starts again.

**Benefits of machine learning:**

* **Automating tasks:** ML can automate repetitive tasks, saving time and resources.
* **Data-driv

# **Now chat template**

In [19]:
chat = [{"role":"user", "content":"Write a program in python to print hello world"}]

In [30]:
text = chat[0]["content"]

In [31]:
token = tokenizer.apply_chat_template(chat, add_generation_prompt=True, tokenize=False)

In [36]:
input_ids = tokenizer.encode(token, add_special_tokens=False, return_tensors="pt").to("cuda")

In [38]:
output = model.generate(input_ids=input_ids, max_new_tokens=512)

In [39]:
output

tensor([[     2,    106,   1645,    108,   5559,    476,   2733,    575,  17706,
            577,   4152,  25612,   2134,    107,    108,    106,   2516,    108,
           1917,   7774,    108,   1431,    885,   4521,   2134,  47347,    108,
           1917,    109,    688,   6140,  66058,    109,   1917,    108,   4521,
           2134, 235341,    108,   1917,    109,    688,  32729,  66058,    109,
         235287,   4103,   1431, 114970,    603,    476,   6233, 235290,    473,
          21237,   1411,    674,  26371,    573,   2764,   9916,    577,    573,
          10647, 235265,    108, 235287,   4103, 235281,   4521,   2134,   4496,
         235376,    603,    573,   2067,    674,    783,   1938,    577,   4152,
         235265,    108, 235287,    714,   4103,   1431, 114970,   1411,    877,
           2409,    573,   4103,    905,   1149,  52106, 235376,   2370,    576,
            573,   2067,   4018,    577,   5920,    665,    604,  17320, 235265,
            108, 235287,    

In [41]:
response = tokenizer.decode(output[0])

In [42]:
print(response)

<bos><start_of_turn>user
Write a program in python to print hello world<end_of_turn>
<start_of_turn>model
```python
print("Hello world!")
```

**Output:**

```
Hello world!
```

**Explanation:**

* `print()` is a built-in Python function that prints the given argument to the console.
* `"Hello world!"` is the string that we want to print.
* The `print()` function will call the `__str__()` method of the string object to format it for printing.
* The `__str__()` method returns the string with the `Hello world!` message.

**Note:**

* The `print()` function can also take multiple arguments, which will be separated by spaces.
* You can also use the `\n` character to insert a newline character in the output.<eos>


# **Now asking the model for a complex code **

In [43]:
chat = [{"role":"user", "content":"Write a program to train logistic regression model"}]

In [44]:
text = chat[0]["content"]

In [45]:
token = tokenizer.apply_chat_template(chat, add_generation_prompt=True, tokenize=False)

In [46]:
input_ids = tokenizer.encode(token, add_special_tokens=False, return_tensors="pt").to("cuda")

In [47]:
output = model.generate(input_ids=input_ids, max_new_tokens=512)

In [48]:
output

tensor([[     2,    106,   1645,    108,   5559,    476,   2733,    577,   6588,
          77606,  26221,   2091,    107,    108,    106,   2516,    108,   1917,
           7774,    108,    809,  26103,    685,  15395,    108,    809,  13168,
            685,   5677,    108,   2273,  40296, 235265,   2516, 235298,  25159,
           1635,   6588, 235298,   2195, 235298,   6860,    108,   2273,  40296,
         235265,  15842, 235298,   2516,   1635, 133205,  64384,    108,   2273,
          40296, 235265,  30918,   1635,  14998, 235298,   9439,    109, 235345,
          17284,    573,   1423,    108,   1259,    589,  15395, 235265,   1229,
         235298,  14019,   1101,   1259, 235265,  14019,   1685,    109, 235345,
          36231,    573,   1423,   1280,   4770,    578,   8603,   9032,    108,
         235356, 235298,   8297, 235269,   1576, 235298,   2195, 235269,    597,
         235298,   8297, 235269,    597, 235298,   2195,    589,   6588, 235298,
           2195, 235298,   6

In [49]:
response = tokenizer.decode(output[0])

In [50]:
print(response)

<bos><start_of_turn>user
Write a program to train logistic regression model<end_of_turn>
<start_of_turn>model
```python
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load the data
data = pd.read_csv('data.csv')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data.drop('target', axis=1), data['target'], test_size=0.2, random_state=42)

# Create the logistic regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Evaluate the model on the testing set
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Print some information about the model
print('Parameters:')
print(model.coef_)
print('Intercept:', model.intercept_)

# Save the model for future use
model.save('logistic_regression_model.pkl')
```

**data

# **Getting the specific output from the model**

In [54]:
import re

start_pattern = r"```python"
end_pattern = r"```"

pattern = re.compile(rf"{start_pattern}(.*?){end_pattern}", re.DOTALL)

match = pattern.search(response)

if match:
  hii = match.group(1).strip()
  print(hii)
else:
  print("No match found")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load the data
data = pd.read_csv('data.csv')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data.drop('target', axis=1), data['target'], test_size=0.2, random_state=42)

# Create the logistic regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Evaluate the model on the testing set
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Print some information about the model
print('Parameters:')
print(model.coef_)
print('Intercept:', model.intercept_)

# Save the model for future use
model.save('logistic_regression_model.pkl')
